### ISSUE TITLE
Node 'INSTANCE' doesn't inherit from 'FRAME' properties

### ISSUE THREAD

**Issue by aloisdeniel** [Morglod/figma-api#1]
An `INSTANCE` node should inherits from `FRAME`, but in `ast-types.d.ts` the type is defined as a `VECTOR` : 

```typescript
export declare type INSTANCE<ComponentID = string> = VECTOR & {
    /** ID of component that this instance came from, refers to components table (see endpoints section below) */
    componentId: ComponentID;
};
```

**Comment by Morglod** [comment]
Fixed in https://github.com/Morglod/figma-api/commit/8223858a2c9af008782e910ead5304f9bf0f5fae `1.1.7` version

**Comment by aloisdeniel** [comment]
Thanks, their is also a missing `name` property at the `GetFileResult`level.

**Comment by Morglod** [comment]
@aloisdeniel 
fixed in https://github.com/Morglod/figma-api/commit/55322aad67c35b1a7d15ec4980086b29d075282e `1.1.8` version
