### ISSUE TITLE
type for component set (for multiple variants) is missing

### ISSUE THREAD

**Issue by tilman** [Morglod/figma-api#10]
missing the following type: Figma.Node<"COMPONENT_SET">;
in JSON: type:'COMPONENT_SET'

**Comment by didoo** [comment]
@tilman I have added in #13 (and documented in #12), can you check if this is what you needed?

**Comment by tilman** [comment]
Great work with #13 that was something I was missing as well. But with this Issue I wanted to address something else. What was missing are the types for a COMPONENT_SET node. I can only see and use the COMPONENT type. If I'm not wrong it should be related to this file & line: https://github.com/Morglod/figma-api/blob/58030cfe9a962f0e6d40c2c75e5bdf11238ac7e1/src/ast-types.ts#L779

I was not sure if it is only this one type which is missing or if there is some logic needed as well?

**Comment by didoo** [comment]
@tilman ok, now I get it. submitted PR on #17
